import type { Metadata } from "next";
import Header from "../layouts/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   /*  <html lang="en"> */
  <div>
    <Header/>
    {children}
  </div>
    
    
  /*   </html> */
  );
}
